import { useState, useMemo } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ShoppingCart, Calendar, DollarSign, Hash, Wallet, Tags, FileText, Check, ArrowRight } from "lucide-react";
import { useFinance } from "@/contexts/FinanceContext";
import { ACCOUNT_TYPE_LABELS, formatCurrency } from "@/types/finance";
import { cn, getDueDate } from "@/lib/utils";
import { toast } from "sonner";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";